baseURL = 'https://owlmaps.github.io/uacontrolmap-timelines'
languageCode = 'en-us'
title = 'UAControlMap Timelines'

disableKinds = ['taxonomy', 'term', 'categories']
cleanDestinationDir = true

[security]
	[security.exec]
		allow = ['^go$', '^npx$', '^postcss$', '^babel$']

